services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - capstone

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    environment:
      GIN_MODE: "release"
      DB_DSN: "postgres://postgres:postgres@db:5432/postgres"
      JWT_SECRET_KEY: "jwt-secret-key"
    networks:
      - capstone
    depends_on:
      - db

networks:
  capstone:
